[build-system]
requires = [
    "setuptools",
    "setuptools-scm",
    "wheel",
    "torch>=1.9.0"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
local_scheme = "node-and-date"
write_to = "./cola/version.py"